Title: Excel
Standards:
  - 
    Title: Excel
    UID: 8d20f27d-b8ed-484e-be3c-8f5c05f73a9d
    Description: Organize, find insights, and communicate findings using advanced spreadsheet capabilites in Microsoft Excel.
    SuccessCriteria:
      - Load various types of data files into Excel 
      - Clean and prepare data with Excel 
      - Analyze data with Excel
    ContentFiles:
      - Type: Lesson
        UID: 7ac9327a-b56a-45c2-b847-f8e1694688bc
        Path: /excel-lessons/overview.md
      - Type: Lesson
        UID: c9aaa4f5-fc32-4134-984d-1c6f02702cf9
        Path: /excel-lessons/data-importing.md
      - Type: Lesson
        UID: 5eb1a2ee-c8ea-48cd-945c-a312b49cb7a5
        Path: /excel-lessons/data-cleaning.md
      - Type: Lesson
        UID: 120aa273-bea4-4315-9349-efb835f809d5
        Path: /excel-lessons/columns.md
      - Type: Lesson
        UID: f62115d1-1c66-4566-87b2-a5178580965b
        Path: /excel-lessons/lookups.md
      - Type: Lesson
        UID: 306c12c1-f017-4f83-b4c5-8f4641b0c078
        Path: /excel-lessons/index-match.md
      - Type: Lesson
        UID: 2974faea-d8e3-4428-8391-53f55af42798
        Path: /excel-lessons/pivot-tables.md
      - Type: Lesson
        UID: 5e458891-f76b-4f3f-8672-601803efcf7b
        Path: /excel-lessons/more-pivot-tables.md     
      - Type: Checkpoint
        Path: /excel-lessons/checkpoint.md
        UID: 12b395fc-2144-4ca5-b050-413461741b85
        Autoscore: false
